version: "3"
services:
    # autostore-frontend:
    #     ports:
    #         - "3000:3000"
    #     build:
    #         context: frontend
    #         dockerfile: Dockerfile
    #     networks:
    #         - uphill-net
    #     depends_on:
    #         - autostore-backend
    #     links:
    #         - autostore-backend


    autostore-backend:
        build:
            context: backend
            dockerfile: Dockerfile
        ports:
            - "8081:8080"
        networks:
            - uphill-net
        depends_on:
            - mysql-storage
        links:
            - mysql-storage

    mysql-storage:
        image: mysql:5.7.35
        networks:
            - uphill-net
        environment:
            - MYSQL_USER=backend
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=admin
            - MYSQL_DATABASE=uphill
        volumes:
            - "./database/startup.sql:/docker-entrypoint-initdb.d/init.sql"
        
networks:
    uphill-net:
        driver: bridge