#!/bin/sh

# This script cleans all the existing containers, images and volumes
# Should be used with caution

sudo docker stop $(docker ps -a -q)
sudo docker rm $(docker ps -a -q)
sudo docker rmi $(docker images -q)
sudo docker volume prune -f